<template>
    <div>
        <div v-if="annualAccounts.length === 0">{{ $t('competitor.bottom-menu.info.no-finance') }}</div>
        <div v-else>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.payroll-gross-name')"
                :tooltip="$t('finance-tab.ratios.payroll-gross')"
                :func="payrollToGrossSales"
                :unit="'%'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.gross-workforce-name')"
                :tooltip="$t('finance-tab.ratios.gross-workforce')"
                :func="grossSalesToWorkForce"
                :more="true"
                :then="100000"
                :unit="'€'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.gross-sub-workforce-name')"
                :tooltip="$t('finance-tab.ratios.gross-sub-workforce')"
                :func="grossSubcontractWorkforce"
                :unit="'€'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.operating-gross-name')"
                :tooltip="$t('finance-tab.ratios.operating-gross')"
                :func="operatingResultToGrossSales"
                :more="true"
                :then="10"
                :unit="'%'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.deficit-equity-name')"
                :tooltip="$t('finance-tab.ratios.deficit-equity')"
                :func="deficitToEquity"
                :more="false"
                :then="50"
                :unit="'%'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.dividends-result-name')"
                :tooltip="$t('finance-tab.ratios.dividends-result')"
                :func="dividendsToNetResult"
                :unit="'%'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.profit-payroll-name')"
                :tooltip="$t('finance-tab.ratios.profit-payroll')"
                :func="profitPayroll"
                :unit="'%'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.payroll-workforce-name')"
                :tooltip="$t('finance-tab.ratios.payroll-workforce')"
                :func="payrollToWorkforce"
                :unit="'€'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.rnd-payroll-name')"
                :tooltip="$t('finance-tab.ratios.rnd-payroll')"
                :func="researchTaxToPayroll"
                :unit="'%'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.net-result-equity-name')"
                :tooltip="$t('finance-tab.ratios.net-result-equity')"
                :func="netResultToEquity"
                :unit="'%'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.net-result-gross-name')"
                :tooltip="$t('finance-tab.ratios.net-result-gross')"
                :func="netResultToGrossSales"
                :unit="'%'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.gross-margin-ratio-name')"
                :tooltip="$t('finance-tab.ratios.gross-margin-ratio')"
                :func="grossMarginRatio"
                :unit="'€'"
            ></FinanceMonthlyRatiosComponent>
            <br>
            <FinanceMonthlyRatiosComponent
                :prevYear="prevYear"
                :displayName="$t('finance-tab.ratios.working-capital-requirements-name')"
                :tooltip="$t('finance-tab.ratios.working-capital-requirements')"
                :func="workingCapitalRequirements"
                :unit="'€'"
            ></FinanceMonthlyRatiosComponent>
        </div>
    </div>
</template>
<script lang="ts" src="./finance-ratios.component.ts">
</script>
<style scoped>

</style>

